futurewei-cloud/alcor

scripts/sampleEP2.sh
scripts/sampleEP3.sh
scripts/sampleVpcTest.sh

based on the latest networking namespace contract with mizar-mp CNI, AlcorControlAgent will parse the namespace and perform different actions accordingly. This change includes:
1. update sampleVpcTest.sh to use a network namespace compatible with "ip netns"
2. added sampleEP2.sh and sampleEP3.sh to create the second and third EP. Note that the first EP is created by sampleVpcTest.sh along with first VPC and subnet.

update sample test scripts based on latest networking namespace contract

---

scripts/build.ps1
scripts/build.sh

This PR is to update build scripts in order to support building new microservices for various OS:
- Linux OS (test for Ubuntu 18.04)
- Mac OsX (test for Mac OsX Mojava v10.14)
- Windows 10

Update build scripts to support microservices build on Linux/MacOsX/Windows

---

services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/implement/PortServiceImpl.java

Port Manager uses a set of RestClients to connect to various microservices to achieve or verify network resources. Those RestClients were in AlcorPortManager project but later moved to the AlcorWeb project intended for sharing by other microservices (PR #180). This move causes that those RestClients cannot be scanned by Spring, as a result, they cannot be obtained through SpringContextUtil.
__Proposed Fix__
In order to repair the bug, we propose to add the annotation @componentscan (value= "com.futurewei.alcor.web.restclient") where the RestClient is needed.

[Port Manager] Fix bug where rest client is unachievable from SpringContextUtil

---

schema/proto3/common.proto
schema/proto3/dhcp.proto
schema/proto3/goalstate.proto
schema/proto3/goalstateprovisioner.proto
schema/proto3/port.proto
schema/proto3/securitygroup.proto
schema/proto3/subnet.proto
schema/proto3/vpc.proto

This is the initial schema update to support OVS. The high-level ideas are:
* Added fields needed to support OVS port configuration update
* Added DHCP configuration
* Keep mizar support for so that it is not a major breaking change for Alcor Control Agent, because ACA still using it for its unit/functional tests
NOTE: It is a draft with a lot of "FIXME" comments for internal discussions.

[Schema Update] Schema Support for OVS and DHCP

---

schema/proto3/common.proto
schema/proto3/dhcp.proto
schema/proto3/goalstate.proto
schema/proto3/goalstateprovisioner.proto
schema/proto3/port.proto
schema/proto3/securitygroup.proto
schema/proto3/subnet.proto
schema/proto3/vpc.proto

This schema update PR includes the following changes:
* Reorder fields, and move up important fields 
* Add two version fields, format_version to mark the version of message format, and revision_number to mark the version of message content
* Add a new field call MessageType which could represent full configuration or delta configuration 
Note that this is a breaking change for Alcor Control Agent.

[Schema Update] Add Version Support and Delta/Full Message Type

---

services/mac_manager/src/main/resources/application.properties
services/node_manager/src/main/resources/application.properties
services/port_manager/src/main/resources/application.properties
services/private_ip_manager/src/main/resources/application.properties
services/route_manager/src/main/resources/application.properties
services/subnet_manager/src/main/resources/application.properties
services/vpc_manager/src/main/resources/application.properties

__Context__
It takes extensive time (45+ minutes) to complete one build and its test. This significantly reduce the development velocity as developer needs to wait that long to see if a build is successful.
__Fix__
The ignite server address is currently pointed to some local env, which delays the up-time of controller a few seconds for every UT that tests web layer. The fix is to revert the Ignite server address to a default localhost.
After the fix, the expected build/test time is reduced from 45+ minutes to less than 5 minutes.

[Build Fix] Reduce Controller Build Time from 45+ to <5 minutes

---

web/src/main/java/com/futurewei/alcor/web/entity/dataplane/InternalDPMResultNB.java

This PR adds a new class of Data Plane Manager (DPM) response the includes per-resource programming status and elapse time.

[Data-Plane Manager] Add New Response Class for DPM

---

services/port_manager/src/main/java/com/futurewei/alcor/portmanager/entity/PortNeighbors.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/proxy/SecurityGroupManagerProxy.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/repo/PortRepository.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/implement/PortServiceImpl.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/util/NetworkConfigurationUtil.java

This PR proposes fix to a few Port Manager bugs:
* Delete Port API doesn't correctly update neighborCache resulting in legacy ports in neighborCache. The root cause is that update NeighborCache doesn't use the correct key for query
* Remove duplicated binding between port and security groups for bulk creation
* Remove redundant neighbor_info for ports on the same host

[Port Manager] Bug Fixes for Delete Ports, Duplicated Port-SG Binding

---

services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/repo/SecurityGroupBindingsRepository.java
services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/repo/SecurityGroupRepository.java
services/security_group_manager/src/test/java/com/futurewei/alcor/securitygroup/controller/SecurityGroupTest.java

__Context__
Root Cause Analysis to Issue #264:
IgniteClient and ignite server have only one connection, and the transaction is at the connection level, so when a client opens multiple transactions at the same time, only one transaction will be returned. After the first transaction is committed, errors such as "Transaction not found" will not be reported when the subsequent transaction commits.
__Fix__
This PR proposes a fix to the bug by adding _synchronized_ key word to the repo method.

RCA of Issue #264 with Fix of Port-SG Concurrent binding

---

.github/workflows/maven.yml
lib/pom.xml
pom.xml
schema/pom.xml
services/api_gateway/pom.xml
services/mac_manager/pom.xml
services/node_manager/pom.xml
services/port_manager/pom.xml
services/private_ip_manager/pom.xml
services/route_manager/pom.xml
services/security_group_manager/pom.xml
services/subnet_manager/pom.xml
services/vpc_manager/pom.xml
web/pom.xml

__Context__
The Alcor project uses JDK8 (LTS), which was released back on March 2014 and will be ceased for public updates by December 2020. 
The latest LTS version is JDK11 (18.9), which comes with many new features including new improvement on startup, performance, memory usage, diagnostics and productivity. Notably, new features includes
- Modules
- New profiling and diagnostics features including Java Flight Recorder, Java Mission Control, Unified loggging, low-overhead heap profiling, and StackWalker. Java Flight Recorder and Java Mission Control are two commercial features which were only available in Oracle JDK before JDK11.
- New GC mechanisms, for example, ZGC was only available in the commercial version of Oracle JDK but now available in OpenSDK 11.
- Most important to Alcor …

Upgrade Alcor Project to Use OpenJDK 11 LTS

---

lib/pom.xml
lib/src/main/java/com/futurewei/alcor/common/stats/DurationStatistics.java
lib/src/main/java/com/futurewei/alcor/common/stats/StatisticsAspect.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/controller/PortController.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/repo/PortRepository.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/implement/PortServiceImpl.java
web/src/main/java/com/futurewei/alcor/web/restclient/DataPlaneManagerRestClient.java
web/src/main/java/com/futurewei/alcor/web/restclient/IpManagerRestClient.java
web/src/main/java/com/futurewei/alcor/web/restclient/MacManagerRestClient.java
web/src/main/java/com/futurewei/alcor/web/restclient/NodeManagerRestClient.java
web/src/main/java/com/futurewei/alcor/web/restclient/RouteManagerRestClient.java
web/src/main/java/com/futurewei/alcor/web/restclient/SecurityGroupManagerRestClient.java
web/src/main/java/com/futurewei/alcor/web/restclient/SubnetManagerRestClient.java
web/src/main/java/com/futurewei/alcor/web/restclient/VpcManagerRestClient.java

This PR proposes the following changes:
- Introduce a new annotation to keep track of method elapse time
- Record Web/Service/Repo layers of port creation
- Record elapse time of downstream microservices 
- Identify a potential bottleneck in one of downstream microservices

Add performance statistics for port manager

---

services/api_gateway/src/main/resources/application.properties
services/elastic_ip_manager/src/main/resources/application.properties
services/mac_manager/src/main/resources/application.properties
services/node_manager/src/main/resources/application.properties
services/port_manager/src/main/resources/application.properties
services/private_ip_manager/src/main/resources/application.properties
services/route_manager/src/main/resources/application.properties
services/security_group_manager/src/main/resources/application.properties
services/subnet_manager/src/main/resources/application.properties
services/vpc_manager/src/main/resources/application.properties

This PR is mainly about enable all micro services to use ignite thin client mode

[Ignite] Set Ignite Thin Client as the Default Client

---

services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/route/QuotaRouteConfiguration.java
services/api_gateway/src/main/resources/application.properties
services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/controller/SecurityGroupController.java
services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/service/SecurityGroupService.java
services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/service/implement/SecurityGroupServiceImpl.java
services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/controller/QuotaController.java
web/src/main/java/com/futurewei/alcor/web/entity/quota/QuotaEntity.java
web/src/main/java/com/futurewei/alcor/web/entity/quota/QuotaWebJson.java
web/src/main/java/com/futurewei/alcor/web/entity/securitygroup/SecurityGroup.java
web/src/main/java/com/futurewei/alcor/web/entity/securitygroup/SecurityGroupJson.java
web/src/main/java/com/futurewei/alcor/web/entity/securitygroup/SecurityGroupRule.java
web/src/main/java/com/futurewei/alcor/web/entity/securitygroup/SecurityGroupRuleJson.java
web/src/main/java/com/futurewei/alcor/web/entity/securitygroup/SecurityGroupsJson.java

This PR proposes the following changes to bridge the gap for Nova Integration:
- Add quota entity classes, quota routes in API GW, and quota web controller to return default quota for any given project. Note that it is temporarily hosted in VPC Mgr and will be moved to a new Quota Mgr.
- Add a new web class SecurityGroupsJson to show an array of SGs in the List SG API
- Remove toString in SG web classes (which caused integration failure)
- Fix API GW application properties

[Nova Integration]Add Quota Web Controller and Update List SG API

---

lib/src/main/java/com/futurewei/alcor/common/db/IDistributedLock.java
lib/src/main/java/com/futurewei/alcor/common/db/ignite/IgniteClientDistributedLock.java
lib/src/main/java/com/futurewei/alcor/common/db/ignite/IgniteDistributedLock.java
lib/src/main/java/com/futurewei/alcor/common/db/redis/RedisDistributedLock.java

This PR fix a bug in distribution lock common lib:
-   Now each distribution lock methods combine a db lock key, it may cause different names and can't remove this lock. 
-   So add a common method to combine a lock key name.

[Common Lib] Fix Distribution Lock Name Bug

---

web/src/main/java/com/futurewei/alcor/web/restclient/ElasticIpManagerRestClient.java

This PR proposes a hotfix to a missing qualifying bean issue introduced by a recent change. 
__Client Logs__
The symptom is DELETE /ports/<port_id> call failed with the following exception
2020-07-22 11:29:19.604 13272 DEBUG neutronclient.v2_0.client [-] Error message: {"timestamp":"2020-07-22T17:49:52.661+0000","status":500,"error":"Internal Server Error","message":"No qualifying bean of type 'com.futurewei.alcor.web.restclient.ElasticIpManagerRestClient' available","path":"/project/f282163e-0698-40d0-8da9-07661a2ce609/ports/f6a00f29-d997-476e-aa1b-77e55bf8cfdc"} _handle_fault_response /usr/lib/python2.7/dist-packages/neutronclient/v2_0/client.py:259
__Server Logs__
2020-07-22 19:34:10.521  INFO 1 --- [nio-8080-exec-7] c.f.alcor.common.stats.StatisticsAspect  : …

[Hotfix] Add missing configuration annotation to EIP RestClient

---

lib/src/main/java/com/futurewei/alcor/common/db/ignite/MockIgniteServer.java
lib/src/main/java/com/futurewei/alcor/common/utils/SpringContextUtil.java

1) add implemention of getOrCreateCache(CacheConfiguration<K, V> var1) in IgniteNodeClientMock
2) remove the non-null check of the SpringContextUtil.applicationContext, so that the applicationContext can change normally

[UT Fix] Stabilize SwaggerJsonTest UT

---

lib/src/main/java/com/futurewei/alcor/common/utils/ControllerUtil.java
services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/client/KeystoneClient.java
services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/filter/KeystoneAuthWebFilter.java
services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/proxies/SubnetManagerServiceProxy.java
services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/proxies/VpcManagerServiceProxy.java
services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/subnet/SubnetWebConfiguration.java
services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/subnet/SubnetWebDestinations.java
services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/subnet/SubnetWebHandlers.java
services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/vpc/VpcWebConfiguration.java
services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/vpc/VpcWebDestinations.java
services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/vpc/VpcWebHandlers.java
services/api_gateway/src/test/java/com/futurewei/alcor/apigateway/KeystoneAuthGwFilterTest.java
services/api_gateway/src/test/java/com/futurewei/alcor/apigateway/KeystoneAuthWebFilterTest.java
services/api_gateway/src/test/java/com/futurewei/alcor/apigateway/KeystoneClientTest.java
services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/service/implement/MacServiceImpl.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/controller/PortController.java
services/port_manager/src/main/resources/application.properties
services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/controller/SecurityGroupController.java
services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/controller/SecurityGroupRuleController.java
services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/repo/SecurityGroupRepository.java
services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/service/SecurityGroupRuleService.java
services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/service/SecurityGroupService.java
services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/service/implement/SecurityGroupRuleServiceImpl.java
services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/service/implement/SecurityGroupServiceImpl.java
services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/controller/SubnetController.java
services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/controller/VpcController.java
web/src/main/java/com/futurewei/alcor/web/entity/securitygroup/SecurityGroupRule.java
web/src/main/java/com/futurewei/alcor/web/entity/securitygroup/SecurityGroupRulesJson.java
web/src/main/java/com/futurewei/alcor/web/restclient/ElasticIpManagerRestClient.java

This PR proposes the following changes:
-  remove '-' in projectId to adaptor neutron formater
-  add security group multi params filters
-  rename ether_type to ethertype in SecurityGroupRule
-  fix a ElasticIP client bug
-  add default binding:vif_type=ovs config in port manager 
-  fix openstack dashboard get all project vpcs

[Integration] Fix VPC/Subnet/Port/SG/EIP Misc, and Add SG Query

---

services/elastic_ip_manager/src/main/resources/application.properties
services/mac_manager/src/main/resources/application.properties
services/node_manager/src/main/resources/application.properties
services/port_manager/src/main/resources/application.properties
services/private_ip_manager/src/main/resources/application.properties
services/route_manager/src/main/resources/application.properties
services/security_group_manager/src/main/resources/application.properties
services/subnet_manager/src/main/resources/application.properties
services/vpc_manager/src/main/resources/application.properties

This PR proposes the following fix:
- When a microservice is launched,  an error is thrown that Redis can't connect. It was caused by unnecessary actuator Redis check. This PR by default disables this Redis check.

[Spring Config] Remove Redis Health Check to Avoid Start Service Error

---

schema/proto3/common.proto

This PR updates the GS schema by adding one operation status - pending - so that host agent could acknowledge the reception of GS from DPM,

[Schema] Add Pending Operation Status for Port Operation

---

services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/controller/VpcController.java

Vpc Mgr currently has issues to process a portion of query parameters, e.g. router:external. This is causing some LIST Vpc REST calls don't return valid information, which further triggers client misbehavior. 
__Root Cause__
The root cause is that when generating queryParams, we placed SubnetEntity class, instead of VpcEntity class. 
This PR makes a simple one-line fix.

[Vpc Mgr] Fix LIST Vpc Query Issue

---

services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/controller/GSController.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/ClientOfDPMFailureException.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/utils/GoalStateManager.java
web/src/main/java/com/futurewei/alcor/web/entity/dataplane/NetworkConfiguration.java

This PR enhances DPM logging by adding time cost estimation. It also fixes a NPE issue tracked by Issue #344 in which Port Mgr passes a network configuration with NULL tunnel id causing DPM throw NPE.

[Data-Plane Mgr] Add Time Cost Estimation and Fixed Issue #344

---

lib/src/main/java/com/futurewei/alcor/common/entity/TokenEntity.java
lib/src/main/java/com/futurewei/alcor/common/utils/ControllerUtil.java
lib/src/main/java/com/futurewei/alcor/common/utils/DateUtil.java
services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/client/KeystoneClient.java

This PR fixs an API GW time format bug where the KeyStone data format strings was not thread-safe. This PR uses ThreadLocal variable to make sure two threads can't see each others' ThreadLocal variables.
In a high-stress testing, API GW had a chance of throwing a "java.lang.NumberFormatException" exception, 13 out of a few 10,000 REST API calls.

[API GW] Ensure Thread-safe Date Format Strings

---

services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/filter/KeystoneAuthGwFilter.java
services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/route/ElasticIPRouteConfiguration.java
services/api_gateway/src/main/resources/application.properties
services/elastic_ip_manager/src/main/java/com/futurewei/alcor/elasticipmanager/dao/ElasticIpAllocator.java
services/elastic_ip_manager/src/main/java/com/futurewei/alcor/elasticipmanager/service/implement/ElasticIpServiceImpl.java
services/elastic_ip_manager/src/main/java/com/futurewei/alcor/elasticipmanager/utils/ElasticIpControllerUtils.java
services/elastic_ip_manager/src/test/java/com/futurewei/alcor/elasticipmanager/ElasticIpControllerTests.java
services/elastic_ip_manager/src/test/java/com/futurewei/alcor/elasticipmanager/config/UnitTestConfig.java
web/src/main/java/com/futurewei/alcor/web/entity/elasticip/ElasticIp.java
web/src/main/java/com/futurewei/alcor/web/entity/elasticip/ElasticIpInfo.java
web/src/main/java/com/futurewei/alcor/web/entity/elasticip/ElasticIpPortDetails.java
web/src/main/java/com/futurewei/alcor/web/entity/elasticip/openstack/FloatingIpRequest.java
web/src/main/java/com/futurewei/alcor/web/entity/elasticip/openstack/FloatingIpRequestWrapper.java
web/src/main/java/com/futurewei/alcor/web/entity/elasticip/openstack/FloatingIpResponse.java
web/src/main/java/com/futurewei/alcor/web/entity/elasticip/openstack/FloatingIpResponseWrapper.java
web/src/main/java/com/futurewei/alcor/web/entity/elasticip/openstack/FloatingIpsWrapper.java

This PR includes the following change:
- remove private ip version attribute from EIP
- add port details attribute to EIP
- add floatingip related models
- add transfrom process between EIP and FIP in apigateway
- fix a bug that found in the integration test：allocation availiable buckets bitset should be initialized to false

[Integration] ElasticIP APIs Compatible with OpenStack 

---

lib/src/main/java/com/futurewei/alcor/common/rbac/StrictRbacManager.java

This PR fix RbacManager load rbac config file error in k8s environment.

[Deployment] Fix Rbac Config Load Error in K8s Deployment

---

services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/DatabaseProcessor.java

This PR proposes a quick fix of port update. PM throws a java.lang.IndexOutOfBoundsException when attempting to update DB. 
PM logs:
```
2020-08-31 03:42:08.405 DEBUG 1 --- [-8080-exec-1500] o.a.coyote.http11.Http11InputBuffer   : Received [PUT /project/52f963d1de344f3eb5b8e806bd5ee05c/ports/dbb1e87e-aaa9-4cb3-8c8e-a564fdb76368 HTTP/1.1
Accept: application/json
X-Token-Info: {"token":"gAAAAABfTHGuhQU7-GJT7NDE4zkyP1ZkLdBNXwZnp9X2gbht2obD70UBA8g0LYLzZYdZV2itiTMmwU_7Sp5CcBGo65v-OhIqnOSdcZBIsVvVKcRbNQIcAR3zkNGpsonecaLd9oz7dHX399yEl_CiDj4sBcmw2SluXBWzzapOaxiqt8a917ds0Kc", "expireAt":"2020-08-31T15:42:38.000+0000", "user":"c_rally_6df4772f_6YkGpKrf", "userId":"dfaf5a563eb54182b9a32929b69e332a", "domainId":"default", "domainName":"Default", "projectName":"c_rally_6df4772f_1K5MYMs2", …
```

[Port Mgr] Fix Update Port Exception in DatabaseProcessor

---

web/src/main/java/com/futurewei/alcor/web/entity/dataplane/NeighborInfo.java

This PR address the issue raised by Issue #376. The current hashcode generation method in NeighborInfo Class returns constant value, which is particularly unsuitable for large neighbor scenario. As the performance test by #376, 10K neighbor caused 10+s latency as the same _hashCode_ value forced each entry to be added to the _HashSet_ to compare all the existing entries due to hash conflicts.
This PR proposes the following change:
- Change the hashcode algorithm for NeighborInfo Class

[DPM] Fix Hashcode Bug Causing 10s Latency for 10K Neighbors

---

services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/grpc/DataPlaneClientImpl.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/pulsar/DataPlaneClientImpl.java

This PR proposes a hotfix to DPM:
- Disable pulsar client as enabling it caused a conflict with an existing gRPC client. Both clients inherit from DataPlaneClient and we would need a long-term fix to allow them coexist.
- Autowire gPRC port to a configuration $dataplane.grpc.port.

[Hotfix] Disable Pulsar Client and Fix gRPC Client

---

services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/DatabaseProcessor.java

Current com.futurewei.alcor.portmanager.processor.DataPlaneProcessor expects neighborInfos is always not null, otherwise it throws a NPE resulting in failure of port update operation. However, this assumption doesn't always hold as customer could update any port attributes which is a valid customer scenario.
__Proposed Change__
This PR proposes a simple fix to make sure we verify neighborInfos and always pass the proper value to updatePort method. PM already has appropriate support to persist data when neighborInfos=null.

[Hotfix] Fix Update Port Issue to Handle Null BindingHostId

---

lib/src/main/java/com/futurewei/alcor/common/executor/ThreadPoolExecutorConfig.java

__Performance Tuning__
In a stress test case at high-QPS high concurrency, we observe performance degradation for port update and delete APIs with a success rate barely above 80%. We observe Port Manager throws internal server errors associated with ThreadPoolExecutor with default pool size = 20 while active thread also reaches 20. This indicates that PM used up all the available threads from the pool resulting in rejection of new request.
After raising threshold of corePoolSize and maximumPoolSize, Alcor controller can sustain in the high load. 
We recommend to set corePoolSize = 32, and maximumPoolSize=128. 
__Next Step__
- Investigate to make the configuration a service-level configuration @chenpiaoping 
- Explore thread pool in DPM @Gzure

[Performance] Increase Thread Pool Size to Improve Concurrency

---

scripts/build.sh
services/port_manager/src/main/resources/application.properties
services/route_manager/src/main/java/com/futurewei/alcor/route/service/Impl/NeutronRouterServiceImpl.java
services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/controller/SecurityGroupController.java
services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/repo/PortBindingSecurityGroupRepository.java
services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/utils/RestParameterValidator.java

This PR proposes fixes to four issues
- [RM1] Update Route Manager configuration file by adding a missing new configuration
- [RM2] Route Manager getConnectedSubnets API returns an ConnectedSubnetsWebResponse object instead of NULL
- [SGM3] Fix SG creation issue caused by missing tenant id
- [SGM4] Fix Security Group Deletion API issue caused by extra binding info
- [Script] Update build.sh
__[SGM3] Context of Security Group Creation Issue__
The SG POST API includes a tenant id from Neutron API v2.0 spec. However, some neutron client including CLI and Rally client don't follow API spec closely (or maybe outdated) - the tenant id is missing resulting in failure of SG creation. As a workaround, we decided to assign project id to tenant id when client doesn't pass tenant ID to Security Group …

[Hotfix] Fix SecurityGroup Mgr and Route Mgr Issues

---

services/port_manager/src/main/java/com/futurewei/alcor/portmanager/exception/GetConnectedRouterException.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/exception/VpcTunnelIdInvalid.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/DataPlaneProcessor.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/NetworkConfig.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/PortContext.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/RouterProcessor.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/request/FetchRouterSubnetsRequest.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/implement/PortServiceImpl.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/util/NetworkConfigurationUtil.java
services/port_manager/src/test/java/com/futurewei/alcor/portmanager/config/UnitTestConfig.java
services/port_manager/src/test/java/com/futurewei/alcor/portmanager/util/ResourceBuilder.java
services/route_manager/src/main/java/com/futurewei/alcor/route/config/ConstantsConfig.java
services/route_manager/src/main/java/com/futurewei/alcor/route/service/Impl/NeutronRouterServiceImpl.java
web/src/main/java/com/futurewei/alcor/web/entity/dataplane/NetworkConfiguration.java
web/src/main/java/com/futurewei/alcor/web/entity/route/ConnectedSubnetsWebResponse.java
web/src/main/java/com/futurewei/alcor/web/entity/route/InternalRouterInfo.java
web/src/main/java/com/futurewei/alcor/web/entity/route/Router.java

This PR proposes the following changes to Port Manager and Route Manager to enable L3 routing:
- PM starts using response from GetConnectedSubnet API from RM, and passing down associated router info (including routing table and routing rule)
- RM GetConnectedSubnet API refactor and issue fixes:
- Change ConnectedSubnetsWebResponse to include a list of SubnetEntities, instead of SubnetIds so that PM could pass down all connected subnets to DPM
- Router type fix (should be neutron_router, instead of neutron)
- PM issue fix:
- Fix remote ip in neighbor table to be the ip address of neighbor port, instead of the neighbor port id.

[Microservice] Port Mgr Support L3 Routing with Routing Rules

---

services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/DataPlaneProcessor.java

This PR fixes two issues for L3 routing in PM
- Issue 1: Empty router may be passed down when subnet is not associated to a router
- Issue 2: In the scenario of mixing subnets with and without association to the router, PM may recognize the new port as a neighbor and put itself in the neighbor table

[Port Mgr] Fix L3 Routing Issues for Unassociated Subnets

---

kubernetes/services/api-gateway.yaml
services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/admin/WebServerConfiguration.java
services/api_gateway/src/main/resources/application.properties

__Context__
In current API GW, the default value of HTTP header size and initial line length is 8192 bytes and 4096 bytes, respectively. But they may result in 413 in one of performance testing scenario when Nova server may query hundreds of device ids. 
__Proposed Solution__
This PR add two new settings for HTTP header size and initial line length, and enlarge the default value of header size and initial line length to 16KB and 64KB, respectively, which is enough for most cases.

[API GW] Customize HTTP header config to Unblock Performance Test

---

schema/proto3/auxiliarygateway.proto
schema/proto3/port.proto
schema/proto3/securitygroup.proto
schema/proto3/subnet.proto
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/ovs/DataPlaneServiceImpl.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/ovs/DataPlaneServiceImplNew.java

The contract change provides support for port delete and adds preliminary Zeta support. The change includes:
1. added auxiliarygateway.proto to support generic gateways
1. made AuxGateway generic for all gateways and use "oneof" to store extra info on specific implementation (e.g. zeta).
1. added device_id and device_owner in proto.proto to support port delete scenario
1. added auxiliary_gateway at vpc.proto
1. fix compiler error in DPM because vpc tunnel ID is changed to uint

[Contract] Support Port Delete and Preliminary Support of Zeta GW

---

schema/proto3/auxiliarygateway.proto
schema/proto3/router.proto

This minor contract change includes:
1. added default_routing_table to router configuration - to support the current subnet manager and router design.
2. change from AuxGateway_type to aux_gateway_type in AuxGateway message - proto3 changes upper case field name to lower case during .proto file compile, so the change is to make this field explicitly to lower case and makes it pretty.

[Contract] Add default_routing_table to Router Configuration

---

schema/proto3/common.proto
schema/proto3/dhcp.proto
schema/proto3/neighbor.proto
schema/proto3/port.proto
schema/proto3/router.proto
schema/proto3/securitygroup.proto
schema/proto3/subnet.proto
schema/proto3/vpc.proto
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/config/Config.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/ovs/DataPlaneServiceImpl.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/utils/GoalStateHelper.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/utils/GoalStateManager.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/utils/GoalStateTransformer.java
services/data_plane_manager/src/main/resources/application.properties
services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/utils/DataPlaneManagerUtil.java

This is a contract update which includes the below changes:
1. Updated dns entry and extra dhcp options in subnet.proto, remove the ones in dhcp.proto to avoid duplication
1. Removed default_routing_table in router.proto
1. Removed DPM code to populate network_type from port.proto per number 3 in #386
1. Don't populate format_version and remove that field for all top level resources per number 4 in #386
1. Don't populate project_id and remove that field for all top level resources except vpc
per number 5 in #386
1. Changed from MessageType to UpdateType for all resources per number 6 in #386

[Contract] Update Contract for DNS/Router, Resolve Discrepancy

---

kubernetes/services/only-build-docker.sh

This PR is to simplify the legacy build process by removing useless build step when you want to build the docker image with not all code change needed.
To run it , simply run sh only-build-docker.sh

[Build Tool] Add Script to Build Docker Image for Services

---

services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/DataPlaneManager.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/grpc/DataPlaneClientImpl.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/pulsar/DataPlaneClientImpl.java

By design, Data-plane Manager should allow multiple data plane clients coexist so that we could enable gRPC fast path and MQ scaling path simultaneously. This PR fixes the issue that DPM can't start (commit a893709) when two types of clients were enabled at the same time.

[Hotfix] Fix Issue that gRPC Client and Pulsar Client Can't Coexist

---

web/src/main/java/com/futurewei/alcor/web/rbac/aspect/RbacAspect.java

Verify project id in DB query when no token is passed to Alcor microservices.

[Enhancement] Verify Project Id for DB query

---

legacy/pom.xml
lib/pom.xml

[Dependency] Upgrade Ignite to 2.9.0

---

kubernetes/services/port_manager.yaml
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/cache/LocalCache.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/cache/LocalCacheImpl.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/DataPlaneClient.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/grpc/DataPlaneClientImpl.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/kafka/DataPlaneClientImpl.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/pulsar/DataPlaneClientImpl.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/DpmServiceImpl.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/NeighborService.java
services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/config/TestConfig.java
services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/controller/DpmTest.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/DataPlaneProcessor.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/NeighborProcessor.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/NetworkConfig.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/proxy/DataPlaneManagerProxy.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/request/CreateNetworkConfigRequest.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/request/DeleteNetworkConfigRequest.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/request/FetchPortNeighborRequest.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/request/UpdateNetworkConfigRequest.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/rollback/CreateNetworkConfigRollback.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/rollback/DeleteNetworkConfigRollback.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/rollback/NetworkConfigRollback.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/rollback/UpdateNetworkConfigRollback.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/PortServiceImpl.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/util/RestParameterValidator.java
services/port_manager/src/main/resources/application.properties
web/src/main/java/com/futurewei/alcor/web/entity/route/RouterUpdateInfo.java
web/src/main/java/com/futurewei/alcor/web/restclient/DataPlaneManagerRestClient.java

1. PM uses the new APIs of DPM
2. Remove the usage of deprecating OperationType in PM
3. Refactor update-l3-neighbors API to accept a list of gateway port IDs
4. DPM handles the configuration information of neighbors

[Microservice] Move forward to DPM v2.0 APIs

---

services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/DatabaseProcessor.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/FixedIpsProcessor.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/PortContext.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/PortProcessor.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/repo/NeighborRepository.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/repo/PortRepository.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/repo/SubnetPortsRepository.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/PortServiceImpl.java
services/port_manager/src/test/java/com/futurewei/alcor/portmanager/controller/MockRestClientAndRepository.java

1. One port supports multiple neighbors
2. Fix the failure to update port

One port supports multiple neighbors && Fix the failure to update port

---

services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/SecurityGroupDirectionInvalid.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/SecurityGroupEtherTypeInvalid.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/SecurityGroupProtocolInvalid.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/NeighborService.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/SecurityGroupService.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/DataPlaneProcessor.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/PortContext.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/SecurityGroupProcessor.java

Fix the port creation failure in DPM v2.0.

[HotFix] Port Creation Fix in DPM v2.0

---

scripts/basicTest.sh

basicTest.sh was failing to GET subnet information because the URL did not specify the "project" endpoint/path.

Fix basicTest.sh. /project/ was missing in the subnet query URL.

---

schema/proto3/gateway.proto
schema/proto3/goalstate.proto
schema/proto3/vpc.proto

We moved the gateway configuration as a top level resource recently. This is a followup change to put gateway state into the top level goal state message.

[Schema] Adding Gateway State into GS Message

---

services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/controller/DpmController.java

The PR from @songxiaoyan PR#549 will break DPM.
This PR reverts the change for createNetworkConfiguration from POST to PUT.

[DPM] Revert change back to PUT for createNetworkConfiguration

---

.gitignore
schema/proto3/dhcp.proto

This PR addes a field, `string id = 3;`, to dhcp.proto. 
It has been tested and the unit tests passed. Please refer to the following screenshot.

[Schema] Add Id field in DHCP state

---

schema/proto3/goalstate.proto
schema/proto3/router.proto

This PR provides a simple update of GoalState V2 schema to support multiple same-type resources per host.

[Schema] Support multiple same-type resources per host

---

services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/grpc/DataPlaneClientImpl.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/DpmServiceImpl.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/SubnetService.java

Each port creation generates one unicast GS and one multicast GS. In current implementation, multicast GS only includes neighbor states while lacks of corresponding subnet states. This causes ACA failure to look up neighbor.
This PR proposes a simple fix to add those missing subnet entities, and enable debug-level logging to show GS detail before sending it to ACA.

[Data-Plane Mgr] Fix missing subnet entity in multicast GoalState

---

services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/service/NodeService.java
services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/service/implement/NodeFileLoader.java
services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/utils/NodeManagerConstant.java
services/node_manager/src/test/java/com/futurewei/alcor/nodemanager/controller/NodeControllerTest.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/proxy/NodeManagerProxy.java
services/port_manager/src/test/java/com/futurewei/alcor/portmanager/config/UnitTestConfig.java
web/src/main/java/com/futurewei/alcor/web/entity/node/NodeInfo.java

NMM changes - part 1
* Add ncm_id to NodeInfo.
* Use setNcmId method to set the ncm_id after creating NodeInfo because
otherwise calls to overloaded constructors are resolving to incorrect
ones, or resulting in errors such as constructor is already defined, or
can't resolve constructor.

[Node Metadata Mgr] Add NCM Id field to NodeInfo

---

services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/PortService.java

This PR fixes two missing fields in PortService at DPM so that we could support port creation and port deletion. 
Tracking issue: #103

[Data Plane Mgr] Add device id and owner in PortService

---

scripts/json/updateNode.json
scripts/test/ncmtest.sh
services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/cache/NodeInfoCache.java
services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/controller/NetworkConfigController.java
services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/service/NodeService.java
services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/service/impl/NodeServiceImpl.java
services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/util/Constants.java

* NCM has API to create, delete, update nodeinfo in NCM.
* Bulk API is not tested. 
* NCM needs to have a rest client for NMM to push NodeInfo into NCM and it will come in the next commit.

[Network Config Mgr] Add NodeInfo APIs

---

kubernetes/services/dpm_manager.yaml
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/controller/DpmController.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/DhcpService.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/PortService.java
services/data_plane_manager/src/main/resources/application.properties

This PR proposes temporary fix for the following scenarios:
- Nova sends port update operation with nonempty device_id and device_owner (of value compute:nova). This request should be treated as CREATE from Alcor perspective.
- Nova sends port update operation with empty device_id and device_owner. This request should be treated as DELETE (tracked by Issue #103).
The ultimate fix should be in Port Manager as the resource owner. We proposes this fix as a short-term solution to verify E2E success.

[Data-Plane Mgr] Fix Port Operation Type Mismatch Issue

---

kubernetes/services/node_manager.yaml

The service URL was missing in node manager's kubernetes configuration. This PR adds the two missing URL.

[Deploment] Add DPM service URL in NMM yaml file

---

lib/src/main/java/com/futurewei/alcor/common/utils/CommonUtil.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/DataPlaneProcessor.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/PortContext.java
web/src/main/java/com/futurewei/alcor/web/entity/dataplane/ResourceOperation.java

In PR #602, a new ResourceOperationType field was added in NetworkConfiguration. This PR sets the value of ResourceOperationTypes when building network configuration and passes down to DPM.

[Port Mgr] Support multiple ResourceOperation types

---

services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/DataPlaneProcessor.java

This PR proposes a fix to two "neighbor resource operation type" issue introduced by PR #603.
__Issue Description__
When the network configuration message is constructed, PM needs to initialize the value of ResourceOperationTypes. The previous PR wrongly put _Router_ type as a _Neighbor_ type, which further introduces duplicated neighbor entities in the List<ResourceOperation>.

[Port Mgr] Fix router resource operation type

---

scripts/alcor_services.sh
scripts/busybox-ping-test/alcor_services.ini
scripts/busybox-ping-test/container_ops.py
scripts/busybox-ping-test/create_test_cases.py
scripts/busybox-ping-test/create_test_setup.py
scripts/busybox-ping-test/helper_functions.py
scripts/busybox-ping-test/ping_test.py
scripts/busybox-ping-test/prepare_payload.py

Added features to restart ACA on remote nodes before start of test.
All tests being on AWS machines.

[Test Script] Update busybox ping test to run from Jenkins

---

services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/cache/HostResourceMetadataCache.java
services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/service/impl/GoalStatePersistenceServiceImpl.java

When DPM/TC sends GoalStates, NCM needs to write these GoalStates into its cache, and it was very slow.
For a test with 200 ports on each host and with 2 hosts in total, putting the GoalState into cache took:
```
pushGoalStatesStream : finished putting GS into cache, elapsed time in milliseconds: 1185
...
pushGoalStatesStream : finished putting GS into cache, elapsed time in milliseconds: 9175
```
With this change, which allows transactional support for cache update, and minimizing cache access, the same actions took:
```
pushGoalStatesStream : finished putting GS into cache, elapsed time in milliseconds: 715
.....
pushGoalStatesStream : finished putting GS into cache, elapsed time in milliseconds: 710
```

[Network Config Mgr] Cache Writing Optimization

---

services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/client/gRPC/GoalStateClientImpl.java
services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/server/grpc/GoalStateProvisionerServer.java

This PR does the following:
1. Changes the `GoalStateClientImpl` to singleton model.
2. Implemneted gPRC channel and stub pool in `GoalStateClientImpl`, so that one host IP uses the same channel and stub, if they are healthy.
3. Implemented logic to check gRPC channel status and reconnection(if needed), before sending GoalState messages.
Comparison:
This is a few test result I did for comparing the NCM on master branch(without channel/stub pooling), and with different versions of NCM that I implemented on this branch. 
We can see from column I(Ping Speed(ms) Avg.) that, without any pooling, or even with channel pool(but not stub pool), which is from testcase 8 and 9, the average ping speed is at about ~400ms.
After adding stub pooling, the average ping speed increased to ~200, ~300ms.

[Communication] gRPC channel/stub pool and keepalive for channels

---

services/route_manager/src/main/java/com/futurewei/alcor/route/controller/RouterController.java
services/route_manager/src/main/java/com/futurewei/alcor/route/exception/CanNotFindRouter.java
services/route_manager/src/main/java/com/futurewei/alcor/route/exception/VpcRouterAlreadyExist.java
services/route_manager/src/main/java/com/futurewei/alcor/route/service/Impl/NeutronRouterServiceImpl.java
services/route_manager/src/main/java/com/futurewei/alcor/route/service/Impl/RouterServiceImpl.java
services/route_manager/src/main/java/com/futurewei/alcor/route/service/RouterService.java
services/route_manager/src/main/java/com/futurewei/alcor/route/utils/RouteManagerUtil.java
services/route_manager/src/test/java/com/futurewei/alcor/route/VpcRouterTests.java

Router controller:
getOrCreateVPCRouter
-> rename as 'getVPCRoutercreate', and delete 'create' operation related part
-> Add a new API 'createVPCRouter'
getOrCreateSubnetRouteTable
-> rename as 'getSubnetRouteTable', and delete 'create' operation related part
createNeutronSubnetRouteTable
-> rename as 'createSubnetRouteTable'
getOrCreateVpcRouteTable
-> rename as 'getVpcRouteTable', and delete 'create' operation related part
-> Add a new API 'createVpcRouteTable'

[RM] Separate getOrCreateVPCRouter into GET and POST two APIs

---

services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/controller/SubnetController.java
services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/service/SubnetService.java
services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/service/implement/SubnetServiceImp.java

added try catch to 'delete subnet routing rule in route manager'.
From second part of issue #648

[Subnet] add try catch in delete subnet for subnet routing rule deletion if routing table is not exist

---

kubernetes/services/network_config_manager.yaml

This PR is to add three missing configurations in NCM yaml file. These three configurations were first introduced by PR #670.

[K8s Deployment] Add missing config in NCM yaml file 

---

kubernetes/db/ignite/ignite-deployment.yaml
lib/Dockerfile
lib/ignite.Dockerfile
lib/pom.xml
scripts/deploy.sh
scripts/test-prep.sh
services/node_manager/pom.xml

Ignite v2.10.0 was released on March 2021 with a handful of desirable features to boost Alcor performance. 
Release Note: https://ignite.apache.org/releases/2.10.0/release_notes.html
This upgrade enables us to try out the following features in the next release:
* Java thin-client
- Added thin client Java API - async API
- Added thin client Kubernetes discovery
- Added thin client continuous query
- Added thin client transactions
* Ignite Control Center (https://www.gridgain.com/tryfree#controlcenter)

[Dependency] Upgrade Ignite to 2.10.0

---

lib/pom.xml

Upgrade com.google.guava:guava to version 30.0-jre or later to address some potential security concern. 
Warning message from GitHub:
``
A temp directory creation vulnerability exist in Guava versions prior to 30.0 allowing an attacker with access to the machine to potentially access data in a temporary directory created by the Guava com.google.common.io.Files.createTempDir(). The permissions granted to the directory created default to the standard unix-like /tmp ones, leaving the files open. We recommend updating Guava to version 30.0 or later, or update to Java 7 or later, or to explicitly change the permissions after the creation of the directory if neither are possible.
``

[Dependency] Upgrade guava package to 30.0+

---

kubernetes/createYaml.sh
kubernetes/db/ignite/ignite_alcor.yaml
kubernetes/db/ignite/ignite_alcor_ip.yaml
kubernetes/db/ignite/ignite_alcor_mac.yaml
kubernetes/db/ignite/ignite_alcor_port.yaml
scripts/deployK8sClusterService.sh

- Rather than wait certain time for k8s to be active, now the deployment script will check the status of k8s pod to make sure they are all up and running before continue. Thus can tolerate different deployment situations.
- Fixed some url links for ignite config files.

[Deployment] K8s deployment enhancement

---

kubernetes/services/api-gateway.yaml
kubernetes/services/dpm_manager.yaml
kubernetes/services/elastic_ip_manager.yaml
kubernetes/services/gateway_manager.yaml
kubernetes/services/mac_manager.yaml
kubernetes/services/network_config_manager.yaml
kubernetes/services/node_manager.yaml
kubernetes/services/port_manager.yaml
kubernetes/services/private_ip_manager.yaml
kubernetes/services/quota_manager.yaml
kubernetes/services/route_manager.yaml
kubernetes/services/sg_manager.yaml
kubernetes/services/subnet_manager.yaml
kubernetes/services/vpc_manager.yaml

This PR added in the "namespace" field for alcor services on k8s.
Originally we don't need the  "namespace" field when we deploy with shell script, since they are all in the default namespace.
Now we want to switch use ansible deployment script, it need the "namespace" field in yaml. Since we can actually switch our "default" to other namespaces.

Added in namespace field for ansible deploy script

---

services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/entity/MulticastGoalStateV2.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/NeighborService.java

In this PR,
1. Removed hashset for hostIps from MulticastGoalstateV2. The getter of hostIps replaced by `hostVpcMap.keySet()`
2. Add necessary comments in MulticastGoalstateV2.
These changes have passed the Jenkins test.

[DPM] Remove hostIps hashset from MulticastGoalstateV2

---

kubernetes/services/dpm_manager.yaml

Added additional info for commit #742 
For the DPM application.properties change in #742 , also added them to DPM k8s yaml file. So Alcor in k8s can work smoothly. Other wise we will observe the bellow error when creating subnets.
> Error: Failed to create subnet "10.6.0.0/16" for network "n1": 500 : [{"timestamp":"2022-03-24T21:12:36.151+0000","status":500,"error":"Internal Server Error","message":"502 Bad Gateway: [no body]","path":"/project/ea7140424ac04a4fbc613138c9fec9b7/subnets/1a020230-84f9-4d73-b65e-776f15d81d78/routetable"}]

[Deployment] Add info in k8s yaml

---

kubernetes/db/ignite/ignite_alcor.yaml
kubernetes/db/ignite/ignite_alcor_dpm.yaml
kubernetes/db/ignite/ignite_alcor_ip.yaml
kubernetes/db/ignite/ignite_alcor_mac.yaml
kubernetes/db/ignite/ignite_alcor_ncm.yaml
kubernetes/db/ignite/ignite_alcor_port.yaml
kubernetes/kustomization.yaml

This PR adds the following changes:
- Single Kustomize file to deploy Alcor on Kubernetes.
- Fix ignite DB deployment that required the extra step of activating the DB with Kubectl

Kustomize and Ignite DB yaml Command line args
