.gitignore
scripts/build.sh
scripts/deploy.sh
src/README.md

New in this PR:  Controller could be built and deployed in Mac OS X.

Build and deploy scripts support Mac OS X

---

src/com/futurewei/alcor/controller/logging/FileLogger.java

This PR increases the default size of log file from 1 KB to 10 MB.

Change default size of log file to 10 MB

---

.github/workflows/maven.yml

Update Alcor CI workflow to support build and package of new microservice directories

Update maven CI workflow to support microservices

---

.github/workflows/dockerimage.yml

Docker CI workflow is not in use so disable for now.

[CI/CD] Disable docker CI workflow

---

services/mac_manager/pom.xml
services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/config/SwaggerConfig.java
services/private_ip_manager/pom.xml
services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/config/SwaggerConfig.java
services/route_manager/pom.xml
services/route_manager/src/main/java/com/futurewei/alcor/route/config/SwaggerConfig.java
services/subnet_manager/pom.xml
services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/config/SwaggerConfig.java
services/vpc_manager/pom.xml
services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/config/SwaggerConfig.java

__List of Change__
* Add swagger dependencies
* Move swagger config from test to src
__NOTE__
* Need to execute microservices and access the UI of each microservices via /swagger-ui.html

[Alcor Tools] Set up a Swagger UI

---

README.md
docs/modules/ROOT/pages/comm_protocol/fast_path.adoc
docs/modules/ROOT/pages/comm_protocol/rescue_path.adoc
docs/modules/ROOT/pages/controller.adoc
docs/modules/ROOT/pages/db_services/data_store.adoc
docs/modules/ROOT/pages/deploy_related/deployment.adoc
docs/modules/ROOT/pages/deploy_related/integration_nova.adoc
docs/modules/ROOT/pages/high_level/system_flow.adoc
docs/modules/ROOT/pages/mgmt_services/private_ip_manager.adoc
docs/modules/ROOT/pages/mgmt_services/virtual_mac_manager.adoc
docs/modules/ROOT/pages/mgmt_services/vpc_manager.adoc
docs/modules/ROOT/pages/sys_monitoring/monitoring.adoc
pom.xml
services/route_manager/pom.xml
services/subnet_manager/pom.xml
services/vpc_manager/pom.xml

This PR proposes the following fix:
* Fix broken image links in couple of design docs caused by PR #210 
* Use consistent java version of maven compiler config for VPC/Subnet/Route Manager

[Documentation] Fix Image Links, and Use Consistent Java Version

---

docs/modules/ROOT/pages/mgmt_services/elastic_ip_manager.adoc

This PR offers a design outline of Elastic IP Manager to kick off discussion.

[Documentation] Outline Elastic IP Manager Design

---

README.md
scripts/build_coverage.sh

This PR proposes the following changes:
* Fix the build script for code coverage
* Update CodeCov badge to point to alcor/master.

[Code Coverage] Fix Code Coverage Script and Update CodeCov Badge

---

services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/utils/RestParameterValidator.java
web/src/main/java/com/futurewei/alcor/web/entity/port/PortEntity.java
web/src/main/java/com/futurewei/alcor/web/entity/vpc/VpcWebRequestObject.java
web/src/main/java/com/futurewei/alcor/web/json/filter/JacksonJsonFilter.java

This PR fixes some bugs:
- SecurityGroupRule can not create in Openstack DashBoard
- Vm port can not show in Openstack DashBoard
- Enable portSecurityEnabled

[Integration] Fix Vpc/Port/SecurityGroupRule Misc

---

services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/utils/GoalStateManager.java

This PR adds more logging to debug Issue #328

[Logging] Data-Plane Mgr Add Goal-State Logging Method

---

docs/modules/ROOT/pages/deploy_related/integration_nova.adoc

* Add nova call neutron apis. Aclor can't support some api in current version, i identified in apis table.
* Add two ways to integration with nova.

[Documentation] Proposal of Alcor Integration with Nova

---

services/api_gateway/src/test/java/com/futurewei/alcor/apigateway/KeystoneClientTest.java
web/src/main/java/com/futurewei/alcor/web/entity/vpc/NetworksWebJson.java

This PR fixed a API GW UT error

[API GW] Fix GW UTs Error

---

lib/src/main/java/com/futurewei/alcor/common/entity/CustomerResource.java

This PR adds support tenant_id query

[Microservice] Support Tenant_id Query

---

services/api_gateway/src/main/java/com/futurewei/alcor/apigateway/route/RouterRouteConfiguration.java
services/api_gateway/src/main/resources/application.properties

This PR exposes a set of new APIs for Neutron-compatible routers in API GW.

[New APIs] API GW supports Neutron-Compatible Routers APIs

---

services/quota_manager/pom.xml
services/quota_manager/src/main/java/com/futurewei/alcor/quota/QuotaManagerApplication.java

This PR proposes a fix to quota manager in which its deployment can not work in the K8s environment.

[Deployment] Fix Quota Manager Deployment Issue for K8s

---

services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/utils/MacUtils.java
services/mac_manager/src/main/resources/application.properties
services/mac_manager/src/test/java/com/futurewei/alcor/macmanager/controller/MacControllerTest.java
web/src/main/java/com/futurewei/alcor/web/entity/mac/MacAddress.java

In this PR, we would like to standardize the format of allocated mac addresses by Mac Manager, and resolve the issue listed in PR #450.

[Mac Manager] Standardize Mac Addresses Format

---

services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/DataPlaneClient.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/grpc/DataPlaneClientImpl.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/kafka/DataPlaneClientImpl.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/pulsar/DataPlaneClientImpl.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/config/Config.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/controller/DataPlaneController.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/controller/GSController.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/DataPlaneServiceNew.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/mizar/DataPlaneServiceImpl.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/ovs/DataPlaneServiceImplNew.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/utils/GoalStateManager.java
services/data_plane_manager/src/main/resources/application.properties
services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/controller/GSControllerTest.java
web/src/main/java/com/futurewei/alcor/web/entity/dataplane/refactor/NetworkConfiguration.java
web/src/main/java/com/futurewei/alcor/web/entity/dataplane/v2/NetworkConfiguration.java

This PR proposes new DPM message handling based on new neighbor schema.

[Data Plane Mgr] New Message Contract and Handling 

---

services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/client/grpc/DataPlaneClientImpl.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/controller/DataPlaneController.java

This PR propose a fix to the DPM config autowired issue that caused DPM service start failure.

[Data Plane Mgr] Fix Config Autowired Issue Causing Start Failure

---

services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/DpmServiceImpl.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/PortService.java
services/data_plane_manager/src/test/java/com/futurewei/alcor/dataplane/utils/DataPlaneManagerUtil.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/controller/PortController.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/entity/SubnetPortIds.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/DataPlaneProcessor.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/DatabaseProcessor.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/FixedIpsProcessor.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/MacProcessor.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/NeighborProcessor.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/NodeProcessor.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/PortProcessor.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/RouterProcessor.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/SecurityGroupProcessor.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/VpcProcessor.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/repo/PortRepository.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/PortService.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/PortServiceImpl.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/service/implement/PortServiceImpl.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/util/ArrayUtil.java
services/port_manager/src/test/java/com/futurewei/alcor/portmanager/controller/CreatePortTest.java
services/port_manager/src/test/java/com/futurewei/alcor/portmanager/controller/GetPortTest.java
services/port_manager/src/test/java/com/futurewei/alcor/portmanager/controller/MockRestClientAndRepository.java
services/port_manager/src/test/java/com/futurewei/alcor/portmanager/util/ResourceBuilder.java
web/src/main/java/com/futurewei/alcor/web/entity/elasticip/ElasticIpInfo.java
web/src/main/java/com/futurewei/alcor/web/entity/port/PortEntity.java
web/src/main/java/com/futurewei/alcor/web/entity/port/SubnetPortIds.java

1. Correctly Handle Fields with Null Value for JSON Deserialization
2. Provides the interface to get # of ports in the subnet

Correctly Handle Fields with Null Value for JSON Deserialization

---

services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/DpmServiceImpl.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/service/impl/PortService.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/DataPlaneProcessor.java

Fix issue: https://github.com/futurewei-cloud/alcor/issues/524

[]Fix the problem of failed to create a port

---

lib/pom.xml

Revert the java version downgrade and get back to 11 in common lib.

[Fundamental] Fix Java Version in Common Lib

---

services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/controller/SubnetController.java
services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/service/SubnetService.java
services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/service/implement/SubnetServiceImp.java

When deleting a subnet, we also need to delete its ip range. issue 522 and 523 are caused by not deleting ip range.

Fix Subnet Deletion Issue tracked by #522 and #523

---

services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/controller/DpmController.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/exception/OperationTypeInvalid.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/utils/RestParameterValidator.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/processor/FixedIpsProcessor.java
services/port_manager/src/test/java/com/futurewei/alcor/portmanager/controller/MockRestClientAndRepository.java
services/port_manager/src/test/java/com/futurewei/alcor/portmanager/controller/UpdatePortTest.java
services/port_manager/src/test/java/com/futurewei/alcor/portmanager/util/ResourceBuilder.java
services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/controller/SubnetController.java
services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/service/SubnetService.java
services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/service/implement/SubnetServiceImp.java

Since the delete method of restTemplate does not support carrying body, the put method is used to send delete message.

[Integration] Fix PM/DPM Port Issue tracked by #527

---

services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/cache/RouterSubnetsCache.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/cache/SecurityGroupPortsCache.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/cache/SubnetPortsCache.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/cache/VpcGatewayInfoCache.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/cache/VpcSubnetsCache.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/entity/InternalPorts.java
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/entity/InternalSubnets.java

Declare required entities and caches for DPM's cache.

[DPM] Entities and caches declaration for DPM's cache

---

services/network_config_manager/pom.xml
services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/config/SwaggerConfig.java
services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/controller/NetworkConfigController.java
services/network_config_manager/src/main/resources/application.properties
web/src/main/java/com/futurewei/alcor/web/restclient/NetworkConfigManagerRestClient.java

Swagger instrumentation is not working yet.

[Network Config Mgr] Add NCM REST client for node registration

---

docs/modules/ROOT/workflows/cross_subnet_with_DVR.puml
docs/modules/ROOT/workflows/network_config_manager_workflow.puml
docs/modules/ROOT/workflows/router_e2e_workflow.puml
docs/modules/ROOT/workflows/router_workflow.puml
docs/modules/ROOT/workflows/security_group_workflow.puml
docs/modules/ROOT/workflows/southbound_prog_workflow_v1.puml
docs/modules/ROOT/workflows/southbound_prog_workflow_v2.puml
docs/modules/ROOT/workflows/template.puml
docs/modules/ROOT/workflows/vm_create.puml
docs/modules/ROOT/workflows/vpc_create.puml
kubernetes/services/ignite_config.xml
kubernetes/services/ignite_ip_config.xml
kubernetes/services/ignite_mac_config.xml
kubernetes/services/ignite_port_config.xml
services/data_plane_manager/src/main/java/com/futurewei/alcor/dataplane/config/SwaggerConfig.java
services/elastic_ip_manager/src/main/java/com/futurewei/alcor/elasticipmanager/config/SwaggerConfig.java
services/gateway_manager/src/main/java/com/futurewei/alcor/gatewaymanager/config/SwaggerConfig.java
services/mac_manager/src/main/java/com/futurewei/alcor/macmanager/config/SwaggerConfig.java
services/network_acl_manager/src/main/java/com/futurewei/alcor/networkaclmanager/config/SwaggerConfig.java
services/network_config_manager/src/main/java/com/futurewei/alcor/netwconfigmanager/config/SwaggerConfig.java
services/node_manager/src/main/java/com/futurewei/alcor/nodemanager/config/SwaggerConfig.java
services/port_manager/src/main/java/com/futurewei/alcor/portmanager/config/SwaggerConfig.java
services/private_ip_manager/src/main/java/com/futurewei/alcor/privateipmanager/config/SwaggerConfig.java
services/quota_manager/src/main/java/com/futurewei/alcor/quota/config/SwaggerConfig.java
services/route_manager/src/main/java/com/futurewei/alcor/route/config/SwaggerConfig.java
services/security_group_manager/src/main/java/com/futurewei/alcor/securitygroup/config/SwaggerConfig.java
services/subnet_manager/src/main/java/com/futurewei/alcor/subnet/config/SwaggerConfig.java
services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/config/SwaggerConfig.java

- Change license statement in the puml file
- Correct license statement in the Swagger config.

[License] Updated more license info

---

docs/modules/ROOT/pages/db_services/alcor-transactions.adoc

Add document about transactional semantics for Alcor Caches in general
and spefically about Ignite Caches.

[Documentation] Add Alcor transaction design document

---

services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/GreRangeRepository.java
services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/dao/VxlanRangeRepository.java
services/vpc_manager/src/main/java/com/futurewei/alcor/vpcmanager/service/Impl/SegmentServiceImpl.java

Create default table optimize from about 10 second to about 1 second.

[API Perf Enhancement] Optimize vpc create default segment table

---

services/gateway_manager/src/main/java/com/futurewei/alcor/gatewaymanager/service/GatewayService.java

try to fix unregisterVPC in GM got 500 internalserver error.
#652

[Gateway Mgr] Update GatewayService.java to fix Issue #652

---

services/route_manager/src/main/java/com/futurewei/alcor/route/dao/RouteEntryRepository.java
services/route_manager/src/main/java/com/futurewei/alcor/route/dao/RouteTableRepository.java
services/route_manager/src/main/java/com/futurewei/alcor/route/dao/RouterExtraAttributeRepository.java
services/route_manager/src/main/java/com/futurewei/alcor/route/dao/RouterRepository.java

- Remove try and catch to support concurrent.

[Router Mgr] Remove transaction for a single cache operation

---

kubernetes/services/ignite_config.xml

Part of PR #663 to fix race condition in subnet deletion API.

Add VpcEntity cache TRANSACTIONAL to ignite_config

---

services/pseudo_controller/pom.xml

Fix issue #760    by update dependency org.apache.httpcomponents:httpclient 4.5.13 @zzxgzgz  @DavidLiu506

Fix CVE dependency issue

---

kubernetes/services/api-gateway.yaml
kubernetes/services/dpm_manager.yaml
kubernetes/services/elastic_ip_manager.yaml
kubernetes/services/gateway_manager.yaml
kubernetes/services/mac_manager.yaml
kubernetes/services/network_config_manager.yaml
kubernetes/services/node_manager.yaml
kubernetes/services/port_manager.yaml
kubernetes/services/private_ip_manager.yaml
kubernetes/services/quota_manager.yaml
kubernetes/services/route_manager.yaml
kubernetes/services/sg_manager.yaml
kubernetes/services/subnet_manager.yaml
kubernetes/services/vpc_manager.yaml

This PR fixes the following:
- Alcor services coming up before ignite resulting in them failing to run.

Kubernetes Environment: Wait for Ignite Fix
